"""invites

Revision ID: 2025.11.11_22.29
Revises: 2025.11.10_20.28
Create Date: 2025-11-11 22:29:48.998842

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2025.11.11_22.29"
down_revision: str | None = "2025.11.10_20.28"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "invites",
        "key",
        existing_type=sa.VARCHAR(length=16),
        type_=sa.String(length=8),
        existing_nullable=False,
    )
    op.drop_column("invites", "expires_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invites",
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column(
        "invites",
        "key",
        existing_type=sa.String(length=8),
        type_=sa.VARCHAR(length=16),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
