"""timezone

Revision ID: 2025.11.15_05.10
Revises: 2025.11.15_03.20
Create Date: 2025-11-15 08:10:11.544322

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2025.11.15_05.10"
down_revision: str | None = "2025.11.15_03.20"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "timezone")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events",
        sa.Column("timezone", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
