"""strings

Revision ID: 2025.11.13_13.53
Revises: 2025.11.12_18.56
Create Date: 2025-11-13 16:53:18.456977

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2025.11.13_13.53"
down_revision: str | None = "2025.11.12_18.56"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "events",
        "title",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=128),
        existing_nullable=False,
    )
    op.alter_column(
        "events",
        "description",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.String(length=1024),
        existing_nullable=True,
    )
    op.alter_column(
        "events",
        "cron",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=16),
        existing_nullable=False,
    )
    op.alter_column(
        "groups",
        "name",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=128),
        existing_nullable=False,
    )
    op.alter_column(
        "groups",
        "description",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.String(length=1024),
        existing_nullable=True,
    )
    op.add_column(
        "tags",
        sa.Column("description", sa.String(length=128), nullable=True),
    )
    op.drop_column("tags", "descriptions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tags",
        sa.Column(
            "descriptions",
            sa.VARCHAR(length=128),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("tags", "description")
    op.alter_column(
        "groups",
        "description",
        existing_type=sa.String(length=1024),
        type_=sa.VARCHAR(length=128),
        existing_nullable=True,
    )
    op.alter_column(
        "groups",
        "name",
        existing_type=sa.String(length=128),
        type_=sa.VARCHAR(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "events",
        "cron",
        existing_type=sa.String(length=16),
        type_=sa.VARCHAR(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "events",
        "description",
        existing_type=sa.String(length=1024),
        type_=sa.VARCHAR(length=128),
        existing_nullable=True,
    )
    op.alter_column(
        "events",
        "title",
        existing_type=sa.String(length=128),
        type_=sa.VARCHAR(length=64),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
