"""notnull

Revision ID: 2025.11.12_19.16
Revises: 2025.11.11_22.29
Create Date: 2025-11-12 19:16:11.167772

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2025.11.12_19.16"
down_revision: str | None = "2025.11.11_22.29"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("events", "group_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("events", "group_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
