"""add timzona in tables

Revision ID: 2025.11.10_20.26
Revises: 2025.11.09_08.49
Create Date: 2025-11-10 22:26:04.653218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2025.11.10_20.26'
down_revision: Union[str, None] = '2025.11.09_08.49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('timezone', sa.Integer(), nullable=False))
    op.add_column('groups', sa.Column('timezone', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('timezone', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    op.drop_column('groups', 'timezone')
    op.drop_column('events', 'timezone')
    # ### end Alembic commands ###
